### PR TITLE
Library Features

### PR DESCRIPTION
**Pull request by kunmi02**
Created a library app that shows books and the read status.
I added a button to update the read status of a book, also added buttons to delete a book from the book library
Created a form for adding books.

N/B: Please review the basic requirements for this and add the optional requirements to the nice to have section.

Thank You.

### CODE REVIEW

**Comment by BrittanyBlake** [comment]
### Status: Invalid 🛑 
****
Hi @kunmi02. This pull request has been marked as invalid because have not added a descriptive README file and you have not added a short summary of what you have done in the project to your pull request. These are both requirements and are listed in the [general requirements](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243643/)
****
Please make the required adjustments and submit a new code review request.

### Good Luck and Happy Coding 🍀 👩🏾‍💻

_P.S. If you have any questions about my review or need help, you can message me on slack (@ Brittany Blake)._

**Review by NtwaliHeritier — CHANGES_REQUESTED** [review]
### **STATUS: CHANGES REQUESTED🛑🛑🛑**

Hello @kunmi02 
This is a great project. Codes are very well organized.
However, some changes are requested to make it impeccable.

[REQUIRED]: Use ES6 arrow functions wherever possible. Only the constructor function is supposed to be written using the function keyword.
[REQUIRED]: When I add a book, the display table doesn't add a new row, instead it adds the copy of the old table plus a new row. Kindly fix it.
[OPTIONAL]: Add validations to prevent adding an empty book.
[OPTIONAL]: Save your book in the localStorage.

That's it
tenor (5)

Make the requested changes and ask for another review👍👌
Happy coding💻💻💻💻

**Review by descholar-ceo — CHANGES_REQUESTED** [review]
# Status: Changes Required :vertical_traffic_light: :warning: 
## Hello @kunmi02  :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :red_circle: 
- [x] The installation section in readme file, you said that we need to install dependencies, since we open the project by simply opening the `index.html` file, then there is no need to install dependencies,
- [x] Improve this pull request description please, talk a bit about what you have worked on during this project. Currently you have put `Add buttons` => that's not descriptive at all
- [x] When I add a book, the display table doesn't add a new row, instead it adds the copy of the old table plus a new row. Kindly fix it.
- [x] Add validations to prevent adding an empty book.
- [x] Save your book in the localStorage.
___
_If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._

[GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)

_Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

**Comment by kunmi02** [comment]
> # Status: Changes Required 🚦 ⚠️
> ## Hello @kunmi02 🤝 🤝 🤝
> 👍 This is good to make it this far, your project is really nice, congratulations on the good work you have done so far.
> 👍 I liked that you have tried to implemented the requested changes from the previous review, keep it up, and your project is really almost done.
> 
> #### ⚠️ However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more, that's beacuse this is a learning process, and we are here to help you to become an out-standing developer. See the requested change below 👇 👇 👇
> ### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding
> # [Required Changes] 🔴
> * [ ]  The installation section in readme file, you said that we need to install dependencies, since we open the project by simply opening the `index.html` file, then there is no need to install dependencies,
> * [ ]  Improve this pull request description please, talk a bit about what you have worked on during this project. Currently you have put `Add buttons` => that's not descriptive at all
> * [ ]  When I add a book, the display table doesn't add a new row, instead it adds the copy of the old table plus a new row. Kindly fix it.
> * [ ]  Add validations to prevent adding an empty book.
> * [ ]  Save your book in the localStorage.
> 
> _If anything seems to be unclear to you, reachout and ask anything by commenting on this Pull Request and mention me as [descholar-ceo](https://github.com/descholar-ceo), I will receive a notification and will respond._
> 
> [GitHub](https://github.com/descholar-ceo) | [LinkedIn](https://linkedin.com/in/mugirase-emmanuel) | [Twitter](https://twitter.com/descholar3)
> 
> _Reviewed by [Mugirase Emmanuel (descholar)](https://github.com/descholar-ceo)_

@

**Comment by kunmi02** [comment]
@descholar-ceo 

From my ReadMe, the dependencies install optional if you want to run linters on the code.
The local storage feature is an optional feature for this project. Please check again.

**Review by whiz25 — CHANGES_REQUESTED** [review]
## Changes Required 🙏🏿 
Nice work on the changes requested. I was able to run your app locally.
Let's make some changes before we can merge this PR.
- [x] The delete action doesn't work as expected. Deleting a book adds an instance of the same book while the original book doesn't get removed from the list of books. This is unexpected behavior. Please fix that.
- [x] I got an error in the console when trying to update the read status of a book: `Uncaught TypeError: myLibrary[index] is undefined`


### Martin Afani
#### Slack: whiz25

**Review by mahmoud717 — APPROVED** [review]
### STATUS: APPROVED ✔️ ✔️ 

**hi guys**

**Great job with making all of the requirements. the project is approved, you can go ahead and merge this pull request**

**Pull request merged**
